Add ValidationError check in autogenerated test

diff --git a/build b/build
--- a/build
+++ b/build
@@ -51,6 +51,8 @@ do
     module_test="$tests/test_$module_name.py"
     [ -f "$tests/test_$module_name.py" ] && continue
     echo "from django.test import TestCase"                                         >> $module_test
+    grep 'ValidationError' $module > /dev/null
+    [ $? -eq 0 ] && echo 'from django.core.exceptions import ValidationError'       >> $module_test
     echo "from ..models import $module_name"                                        >> $module_test
     echo ''                                                                         >> $module_test
     echo ''                                                                         >> $module_test
@@ -66,6 +68,14 @@ do
     echo ''                                                                         >> $module_test
     echo "    def test__${module_name}__unicode(self):"                             >> $module_test
     echo '        self.assertEqual(self.subject.__unicode__(), self.subject.name)'  >> $module_test
+    grep 'ValidationError' $module > /dev/null
+    if [ $? -eq 0 ]
+    then
+        echo ''                                                                     >> $module_test
+        echo "    def test__${module_name}__name_choice(self):"                     >> $module_test
+        echo '        with self.assertRaises(ValidationError):'                     >> $module_test
+        echo '            self.subject.save()'                                      >> $module_test
+    fi
 done
 
 
